# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sqybi\GitHub\bilibili_danmaku\danmaku_app\danmaku_app.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_room_number = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_room_number.setObjectName("lineEdit_room_number")
        self.horizontalLayout_2.addWidget(self.lineEdit_room_number)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMouseTracking(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox_queue_size = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_queue_size.sizePolicy().hasHeightForWidth())
        self.spinBox_queue_size.setSizePolicy(sizePolicy)
        self.spinBox_queue_size.setMinimum(1)
        self.spinBox_queue_size.setMaximum(100)
        self.spinBox_queue_size.setProperty("value", 10)
        self.spinBox_queue_size.setObjectName("spinBox_queue_size")
        self.horizontalLayout.addWidget(self.spinBox_queue_size)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMouseTracking(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_app_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_app_id.setObjectName("lineEdit_app_id")
        self.horizontalLayout_3.addWidget(self.lineEdit_app_id)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMouseTracking(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_api_key = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_api_key.setObjectName("lineEdit_api_key")
        self.horizontalLayout_4.addWidget(self.lineEdit_api_key)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMouseTracking(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_secret_key = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_secret_key.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_secret_key.setObjectName("lineEdit_secret_key")
        self.horizontalLayout_5.addWidget(self.lineEdit_secret_key)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMouseTracking(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.spinBox_spd = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_spd.sizePolicy().hasHeightForWidth())
        self.spinBox_spd.setSizePolicy(sizePolicy)
        self.spinBox_spd.setMinimum(0)
        self.spinBox_spd.setMaximum(9)
        self.spinBox_spd.setProperty("value", 9)
        self.spinBox_spd.setObjectName("spinBox_spd")
        self.horizontalLayout_7.addWidget(self.spinBox_spd)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMouseTracking(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.spinBox_pit = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pit.sizePolicy().hasHeightForWidth())
        self.spinBox_pit.setSizePolicy(sizePolicy)
        self.spinBox_pit.setMinimum(0)
        self.spinBox_pit.setMaximum(9)
        self.spinBox_pit.setProperty("value", 5)
        self.spinBox_pit.setObjectName("spinBox_pit")
        self.horizontalLayout_8.addWidget(self.spinBox_pit)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMouseTracking(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.spinBox_vol = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_vol.sizePolicy().hasHeightForWidth())
        self.spinBox_vol.setSizePolicy(sizePolicy)
        self.spinBox_vol.setMinimum(0)
        self.spinBox_vol.setMaximum(15)
        self.spinBox_vol.setProperty("value", 7)
        self.spinBox_vol.setObjectName("spinBox_vol")
        self.horizontalLayout_9.addWidget(self.spinBox_vol)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMouseTracking(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.comboBox_per = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_per.sizePolicy().hasHeightForWidth())
        self.comboBox_per.setSizePolicy(sizePolicy)
        self.comboBox_per.setObjectName("comboBox_per")
        self.comboBox_per.addItem("")
        self.comboBox_per.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_per)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_auto_scroll = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_auto_scroll.sizePolicy().hasHeightForWidth())
        self.checkBox_auto_scroll.setSizePolicy(sizePolicy)
        self.checkBox_auto_scroll.setObjectName("checkBox_auto_scroll")
        self.horizontalLayout_11.addWidget(self.checkBox_auto_scroll)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_status.setFont(font)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "弹幕阅读姬 by sqybi"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "用户"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "弹幕"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "触发语音"))
        self.label.setText(_translate("MainWindow", "房间号"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>最大队列长度<br/>（如不清楚含义请勿修改）</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>百度TTS - APP ID</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>百度TTS - API KEY</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>百度TTS - SECRET KEY</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>百度TTS参数 - 语速</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>百度TTS参数 - 音调</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>百度TTS参数 - 音量</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>百度TTS参数 - 发音人</p></body></html>"))
        self.comboBox_per.setItemText(0, _translate("MainWindow", "女声"))
        self.comboBox_per.setItemText(1, _translate("MainWindow", "男声"))
        self.checkBox_auto_scroll.setText(_translate("MainWindow", "自动滚动"))
        self.pushButton.setText(_translate("MainWindow", "开始接收弹幕"))
        self.label_status.setText(_translate("MainWindow", "❌等待连接到弹幕服务器"))

